#%RAML 1.0
title: Healthcare CRM Experience API
version: v1
baseUri: http://localhost:8081/api/


/patient/migrateClinicalData:
  displayName: migrateClinicalData
  get:
    description: migrate clinical data to Salesforce Health Cloud
    responses:
      200:
        body:
          application/json:
            example: | 
              {
                "message": "The migrate process has finished."
              }
/patient/{id}/migrateClinicalData:
  get:
    description: migrate clinical data to Salesforce Health Cloud
    responses:
      200:
        body:
          application/json:
            example: | 
              {
                "message": "The migrate process for a patient has finished."
              }