#%RAML 0.8
title: healthcare-sfdchealth2fhir-ehr-experience-api
baseUri: http://healthcare-sfhc-experience-api.cloudhub.io/api
version: v1
/patient/migrateClinicalData:
  displayName: migrateClinicalData
  get:
    description: migrate clinical data to Salesforce Health Cloud
    responses:
      200:
        body:
          application/json:
            example: | 
              {
                "message": "The migrate process has finished."
              }
/patient/{id}/migrateClinicalData:
  get:
    description: migrate clinical data to Salesforce Health Cloud
    responses:
      200:
        body:
          application/json:
            example: | 
              {
                "message": "The migrate process for a patient has finished."
              }