#%RAML 0.8
title: healthcare-sfdchealth2fhir-ehr-experience-api
baseUri: http://healthcare-sfhc-experience-api.cloudhub.io/api
version: v1
/patient/migrateClinicalData:
  displayName: migrateClinicalData
  get:
    description: migrate clinical data to Salesforce Health Cloud
    queryParameters:
        mock:
          type: string
          enum: [on, off]
          required: false
    responses:
      200:
        body:
          application/json:
            example: !include experience-api-response.json
