#%RAML 1.0
title: Healthcare EHR to CRM Sync Process API
version: v1
baseUri: http://localhost:8081/api/


/patients/{patientId}/migrateClinicalData:
  displayName: migrateClinicalData
  post:
    description: Migrate clinical data from EHR to CRM
    responses:
      201:
        body:
          application/json:
            example: !include experience-api-response.json
               